apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rmr4xireu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rmr4xireu-go 
  name: rmr4xireu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rmr4xireu-go 
